apiVersion: v1
kind: Secret
metadata:
    name: github-credentials-nodejs-app-example
    namespace: tekton-cicd
    annotations:
        tekton.dev/git-0: https://github.com
type: kubernetes.io/basic-auth
stringData:
    username: gituser
    password: "gitpassword"

---
apiVersion: v1
kind: ServiceAccount
metadata:
    name: githubsa
    namespace: tekton-cicd
secrets:
    - name: github-credentials-nodejs-app-example
