apiVersion: v1
kind: ServiceAccount
metadata:
    name: tekton-cicd-publisher
    namespace: tekton-cicd

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
    name: tekton-cicd-publisher:local-admin
    namespace: tekton-cicd
roleRef:
    apiGroup: rbac.authorization.k8s.io
    kind: ClusterRole
    name: admin
subjects:
    - kind: ServiceAccount
      name: githubsa
      namespace: tekton-cicd

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
    name: tekton-cicd-publisher:editor
    namespace: tekton-cicd
roleRef:
    apiGroup: rbac.authorization.k8s.io
    kind: ClusterRole
    name: edit
subjects:
    - kind: ServiceAccount
      name: tekton-cicd-publisher
      namespace: tekton-cicd-cicd
