apiVersion: tekton.dev/v1alpha1
kind: PipelineRun
metadata:
    name: pipelinerun-tekton-cicd-commit-nodejs-app-example-01
    namespace: tekton-cicd
spec:
    params:
        - name: buildconfig
          value: "myapp"
        - name: deploymentconfig
          value: "myapp"
        - name: namespace
          value: "myapp"
    serviceAccountNames:
        - taskName: app-test
          serviceAccountName: githubsa
        - taskName: app-build
          serviceAccountName: tekton-cicd-publisher
        - taskName: app-deploy
          serviceAccountName: tekton-cicd-publisher
    pipelineRef:
        name: pipeline-tekton-cicd-commit-nodejs-app-example
    resources:
        - name: source-repo
          resourceRef:
              name: git-nodejs-app-example
