apiVersion: tekton.dev/v1alpha1
kind: TriggerBinding
metadata:
    name: triggerbinding-tekton-cicd-nodejs-app-example-pullrequest
    namespace: tekton-cicd
spec:
    params:
        - name: git-repo-url
          value: $(body.repository.url)
        - name: git-repo-name
          value: $(body.repository.name)
        - name: git-revision
          value: "pull/$(body.pull_request.number)/head"
